@Normalize
Feature: Normalize transform - Verify File source data transfer using Normalize transformation

  @NORMALIZE_TEST1 @FILE_SINK_TEST
  Scenario: To verify data is getting transferred from File source to File sink successfully with Normalized fields
    Given Open Datafusion Project to configure pipeline
    When Select plugin: "File" from the plugins list as: "Source"
    When Expand Plugin group in the LHS plugins list: "Transform"
    When Select plugin: "Transpose" from the plugins list as: "Transform"
    Then Connect plugins: "File" and "Transpose" to establish connection
    When Expand Plugin group in the LHS plugins list: "Sink"
    When Select plugin: "File" from the plugins list as: "Sink"
    Then Connect plugins: "Transpose" and "File2" to establish connection
    Then Navigate to the properties page of plugin: "File"
    Then Enter input plugin property: "referenceName" with value: "FileReferenceName"
    Then Enter input plugin property: "path" with value: "normalizeTest1"
    Then Select dropdown plugin property: "format" with option value: "csv"
    Then Click plugin property: "skipHeader"
    Then Click on the Get Schema button
    Then Verify the Output Schema matches the Expected Schema: "normalizeCsvAllDataTypeFileSchema"
    Then Validate "File" plugin properties
    Then Close the Plugin Properties page
    Then Navigate to the properties page of plugin: "Transpose"
    Then Enter Normalize plugin Fields to be Mapped "normalizeFileValidFieldsMapping"
    Then Enter Normalize plugin Fields to be Normalized "normalizeFieldsToBeNormalizedFile"
    Then Select Normalize plugin output schema action: "clear"
    Then Enter Normalize plugin outputSchema "normalizeBQValidOutputSchema"
    Then Validate "Transpose" plugin properties
    Then Close the Plugin Properties page
    Then Navigate to the properties page of plugin: "File2"
    Then Enter input plugin property: "referenceName" with value: "FileReferenceName"
    Then Enter input plugin property: "path" with value: "fileSinkTargetBucket"
    Then Replace input plugin property: "pathSuffix" with value: "yyyy-MM-dd-HH-mm-ss"
    Then Select dropdown plugin property: "format" with option value: "csv"
    Then Click plugin property: "writeHeader"
    Then Validate "File2" plugin properties
    Then Close the Plugin Properties page
    Then Save the pipeline
    Then Preview and run the pipeline
    Then Wait till pipeline preview is in running state
    Then Open and capture pipeline preview logs
    Then Verify the preview run status of pipeline in the logs is "succeeded"
    Then Close the pipeline logs
    Then Close the preview
    Then Deploy the pipeline
    Then Run the Pipeline in Runtime
    Then Wait till pipeline is in running state
    Then Open and capture logs
    Then Verify the pipeline status is "Succeeded"
    Then Close the pipeline logs
    Then Validate output file generated by file sink plugin "fileSinkTargetBucket" is equal to expected output file "normalizeCsvAllDataTypeOutputFile"

  @NORMALIZE_TEST2 @FILE_SINK_TEST @Normalize_Required
  Scenario: To verify data is getting transferred from File source to File sink successfully with different Normalized fields
    Given Open Datafusion Project to configure pipeline
    When Select plugin: "File" from the plugins list as: "Source"
    When Expand Plugin group in the LHS plugins list: "Transform"
    When Select plugin: "Transpose" from the plugins list as: "Transform"
    Then Connect plugins: "File" and "Transpose" to establish connection
    When Expand Plugin group in the LHS plugins list: "Sink"
    When Select plugin: "File" from the plugins list as: "Sink"
    Then Connect plugins: "Transpose" and "File2" to establish connection
    Then Navigate to the properties page of plugin: "File"
    Then Enter input plugin property: "referenceName" with value: "FileReferenceName"
    Then Enter input plugin property: "path" with value: "normalizeTest2"
    Then Select dropdown plugin property: "format" with option value: "csv"
    Then Click plugin property: "skipHeader"
    Then Click on the Get Schema button
    Then Verify the Output Schema matches the Expected Schema: "normalizeCsvFileSchema"
    Then Validate "File" plugin properties
    Then Close the Plugin Properties page
    Then Navigate to the properties page of plugin: "Transpose"
    Then Enter Normalize plugin Fields to be Mapped "normalizeGcsValidFieldsMapping"
    Then Enter Normalize plugin Fields to be Normalized "normalizeFieldsToBeNormalizedGCS"
    Then Select Normalize plugin output schema action: "clear"
    Then Enter Normalize plugin outputSchema "normalizeGcsValidOutputSchema"
    Then Validate "Transpose" plugin properties
    Then Close the Plugin Properties page
    Then Navigate to the properties page of plugin: "File2"
    Then Enter input plugin property: "referenceName" with value: "FileReferenceName"
    Then Enter input plugin property: "path" with value: "fileSinkTargetBucket"
    Then Replace input plugin property: "pathSuffix" with value: "yyyy-MM-dd-HH-mm-ss"
    Then Select dropdown plugin property: "format" with option value: "csv"
    Then Click plugin property: "writeHeader"
    Then Validate "File2" plugin properties
    Then Close the Plugin Properties page
    Then Save the pipeline
    Then Preview and run the pipeline
    Then Wait till pipeline preview is in running state
    Then Open and capture pipeline preview logs
    Then Verify the preview run status of pipeline in the logs is "succeeded"
    Then Close the pipeline logs
    Then Close the preview
    Then Deploy the pipeline
    Then Run the Pipeline in Runtime
    Then Wait till pipeline is in running state
    Then Open and capture logs
    Then Verify the pipeline status is "Succeeded"
    Then Close the pipeline logs
    Then Validate output file generated by file sink plugin "fileSinkTargetBucket" is equal to expected output file "normalizeCsvOutputFile"

  @NORMALIZE_TEST1 @FILE_SINK_TEST @PLUGIN-1231
  Scenario: To verify data is getting transferred from File source to File sink plugin successfully with change in datatype of output schema
    Given Open Datafusion Project to configure pipeline
    When Select plugin: "File" from the plugins list as: "Source"
    When Expand Plugin group in the LHS plugins list: "Transform"
    When Select plugin: "Transpose" from the plugins list as: "Transform"
    Then Connect plugins: "File" and "Transpose" to establish connection
    When Expand Plugin group in the LHS plugins list: "Sink"
    When Select plugin: "File" from the plugins list as: "Sink"
    Then Connect plugins: "Transpose" and "File2" to establish connection
    Then Navigate to the properties page of plugin: "File"
    Then Enter input plugin property: "referenceName" with value: "FileReferenceName"
    Then Enter input plugin property: "path" with value: "normalizeTest1"
    Then Select dropdown plugin property: "format" with option value: "csv"
    Then Click plugin property: "skipHeader"
    Then Click on the Get Schema button
    Then Verify the Output Schema matches the Expected Schema: "normalizeCsvAllDataTypeFileSchema"
    Then Validate "File" plugin properties
    Then Close the Plugin Properties page
    Then Navigate to the properties page of plugin: "Transpose"
    Then Enter Normalize plugin Fields to be Mapped "normalizeFileValidFieldsMapping"
    Then Enter Normalize plugin Fields to be Normalized "normalizeFieldsToBeNormalizedFile"
    Then Select Normalize plugin output schema action: "clear"
    Then Enter Normalize plugin outputSchema "normalizeBQValidDatatypeOutputSchema"
    Then Validate "Transpose" plugin properties
    Then Close the Plugin Properties page
    Then Navigate to the properties page of plugin: "File2"
    Then Enter input plugin property: "referenceName" with value: "FileReferenceName"
    Then Enter input plugin property: "path" with value: "fileSinkTargetBucket"
    Then Replace input plugin property: "pathSuffix" with value: "yyyy-MM-dd-HH-mm-ss"
    Then Select dropdown plugin property: "format" with option value: "csv"
    Then Click plugin property: "writeHeader"
    Then Validate "File2" plugin properties
    Then Close the Plugin Properties page
    Then Save the pipeline
    Then Preview and run the pipeline
    Then Wait till pipeline preview is in running state
    Then Open and capture pipeline preview logs
    Then Verify the preview run status of pipeline in the logs is "succeeded"
    Then Close the pipeline logs
    Then Close the preview
    Then Deploy the pipeline
    Then Run the Pipeline in Runtime
    Then Wait till pipeline is in running state
    Then Open and capture logs
    Then Verify the pipeline status is "Succeeded"
    Then Close the pipeline logs
    Then Validate output file generated by file sink plugin "fileSinkTargetBucket" is equal to expected output file "normalizeCsvAllDataTypeOutputFile"
